---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse 

- src: git@github.com:Artem-Salnikov/ansible-role-vector.git
  scm: git
  version: "1.0.0"
  name: vector 

- src: git@github.com:Artem-Salnikov/ansible-role-lighthouse.git
  scm: git
  version: "1.0.0"
  name: lighthouse
